// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PeppersBpmn.Infrastructure.Persistence;

#nullable disable

namespace PeppersBpmn.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PeppersBpmn.Domain.Entities.ProcessDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CamundaDefinitionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CamundaDeploymentId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("DeployedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ProcessDefinitions");
                });

            modelBuilder.Entity("PeppersBpmn.Domain.Entities.ProcessInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CamundaInstanceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CamundaInstanceId")
                        .IsUnique();

                    b.ToTable("ProcessInstances");
                });

            modelBuilder.Entity("PeppersBpmn.Domain.Entities.ProcessDefinition", b =>
                {
                    b.OwnsOne("PeppersBpmn.Domain.ValueObjects.ProcessKey", "Key", b1 =>
                        {
                            b1.Property<Guid>("ProcessDefinitionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Key");

                            b1.HasKey("ProcessDefinitionId");

                            b1.HasIndex("Value");

                            b1.ToTable("ProcessDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("ProcessDefinitionId");
                        });

                    b.Navigation("Key")
                        .IsRequired();
                });

            modelBuilder.Entity("PeppersBpmn.Domain.Entities.ProcessInstance", b =>
                {
                    b.OwnsOne("PeppersBpmn.Domain.ValueObjects.ProcessKey", "ProcessKey", b1 =>
                        {
                            b1.Property<Guid>("ProcessInstanceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("ProcessKey");

                            b1.HasKey("ProcessInstanceId");

                            b1.HasIndex("Value");

                            b1.ToTable("ProcessInstances");

                            b1.WithOwner()
                                .HasForeignKey("ProcessInstanceId");
                        });

                    b.Navigation("ProcessKey")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
